set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

setw -g mode-keys vi

set -sg escape-time 0
set -g repeat-time 1000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind ^a last-window

unbind %
bind v split-window -h -c '#{pane_current_path}'
unbind '"'
bind s split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind < resize-pane -L 5
bind > resize-pane -R 5
bind - resize-pane -D 5
bind + resize-pane -U 5

unbind r
bind r source-file ~/.tmux.con \; display 'Reloaded!'

set -g mouse on

